#!/bin/bash

mkdir dns_records
cd dns_records

if [ $# -eq 0 ]; 
then
    echo "USAGE: dig_deep <hostfile> [record_types (default: CNAME,TXT,MX,NS)]"
    exit 1
fi

record_types=('CNAME' 'TXT' 'MX' 'NS')
if [[ $2 ]]
then
    record_types=($(echo $2 | tr "," "\n"))
fi

for sub in $(cat ../$1)
do
	for record_type in ${record_types[@]};
	do
        echo "Searching for $record_type in $sub"
		record_file=$(echo $record_type)_records.txt
		dig +short $sub $record_type >> $record_file
	done
done

for record_type in ${record_types[@]};
do
    record_file=$(echo $record_type)_records.txt
    cat $record_file | sort | uniq > temp.txt
    cat temp.txt > $record_file
    rm temp.txt

    if ! [ -s $record_file ]
    then
       #rm $record_file
    fi
done