#!/bin/bash

if [ $# -eq 0 ]; 
then
    echo "USAGE: scan <cidr_or_ip> <additional_ports>"
    exit 1
fi

escaped_cidr=$(echo $1 | tr '/' '_')
hostsfile=$(echo $escaped_cidr)_hosts.txt
masscanfile=$(echo $escaped_cidr)_masscan.json
nmapoutfile=$(echo $escaped_cidr)_nmap.xml

ports=-p21,22,23,5380,443,445,995,1723,2075,2076,3000,3306,3868,4443,5443,5900,6443,7443,8080,8888,8443,9091,9443
if [[ $2 ]]
then
	ports=$ports,$2
fi

# 1. masscan
sudo masscan -v $ports $1 --output-format json --output-file $masscanfile

cat $masscanfile | jq .[].ip | sort | uniq | tr -d '"' > $hostsfile
host_count=$(wc -l $hostsfile | awk '{print $1}')
echo "masscan found $host_count host(s)"

if [[ $host_count > 0 ]]
then
	# 2. dig Reverse DNS lookup
	xargs -L1 --arg-file=$hostsfile dig +short -x > rdns_domains.txt

	ports=$(cat $masscanfile | jq .[].ports[].port | sort | uniq | tr '\n' ',')
	ports=${ports::-1}

	# 3. nmap Banner Grabbing & Fingerptinting
	sudo nmap -oX $nmapoutfile --webxml -O -sV -sC -p $ports -iL $hostsfile
fi