#!/bin/bash

while (( "$#" )); do
    case "$1" in
        -t|--target)
			if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        		TARGET=$2
        		shift 2
      		else
        		echo "Error: Argument for $1 is missing" >&2
        		exit 1
      		fi
      	;;
		-f|--file)
      		if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        		TARGET_FILE=$2
				shift 2
			else
				echo "Error: Argument for $1 is missing" >&2
				exit 1
			fi
		;;
		-p|--ports)
			if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
				ADDITIONAL_PORTS=$2
				shift 2
			else
				echo "Error: Argument for $1 is missing" >&2
				exit 1
			fi
		;;
		-*|--*=) # unsupported flags
				echo "Error: Unsupported flag $1" >&2
			exit 1
		;;
	esac
done

scan_target() {
    echo "Scanning $1"
    echo "Ports: $ports"
    escaped_cidr=$(echo $1 | tr '/' '_')
    hostsfile=$(echo $escaped_cidr)_hosts.txt
    masscanfile=$(echo $escaped_cidr)_masscan.json
    nmapoutfile=$(echo $escaped_cidr)_nmap.xml

    mkdir $escaped_cidr 2>/dev/null
    cd $escaped_cidr

    datestamp=$(date +%Y%m%d)
    mkdir $datestamp 2>/dev/null
    cd $datestamp

    sudo masscan $ports $1 --output-format json --output-file $masscanfile

    cat $masscanfile | jq .[].ip | sort | uniq | tr -d '"' > $hostsfile
    host_count=$(wc -l $hostsfile | awk '{print $1}')
    echo "masscan found $host_count host(s)"

    if [[ $host_count > 0 ]]
    then
        found_ports=$(cat $masscanfile | jq .[].ports[].port | sort | uniq | tr '\n' ',')
        found_ports=${found_ports::-1}

        sudo nmap -O -sSVC -p $found_ports -iL $hostsfile -oX $nmapoutfile --webxml
    fi

    rm $hostsfile
}

if [[ -z $TARGET && -z $TARGET_FILE ]];
then
    echo "USAGE: scan [-t <cidr_or_ip>|-f <targets_file>] [-p <additional_ports>]"
    echo "No targets provided" >&2
    exit 1
fi

rce="1090,1098,1099,4444,11099,47001,47002,10999,7000,7001,7002,7003,7004,8000,8001,8002,8003,9001,9002,9003,9503,7070,7071,45000,45001,8686,9012,50500,4848,11111,4445,4786,5555,5556"
dbms="1433,1434,4022,5432,3306,27017,27018,27019,27080,28017,1521,1630,3938,6379,9092,2100,5984"
docker="2375,2376,5000,6443,10250,10255"
ports="-p21,22,23,25,43,53,69,6780,81,88,110,111,135,139,161,162,389,636443,445,541,554,995,1080,1723,1900,2000,2049,2075,2076,2083,3000,3389,3868,4443,5380,5443,5601,5900,5985,7443,8069,8080,8172,8880,8443,9000,9091,9200,9443,10000,$dbms,$docker,$rce"

echo "Default Ports: $ports"
if [[ $ADDITIONAL_PORTS ]]
then
    echo "Additional Ports: $ADDITIONAL_PORTS"
    ports=$ports,$ADDITIONAL_PORTS
fi

if [ -n "$TARGET" ];
then
    scan_target $TARGET
else
    for target in $(cat $TARGET_FILE)
    do
	scan_target $target
	cd ../..
    done
fi
