#!/bin/bash

ports=-p21,22,23,5380,443,445,995,1723,2075,2076,3000,3306,3868,4443,5443,5900,6443,7443,8080,8888,8443,9091,9443

escaped_cidr=$(echo $1 | tr '/' '_')
hostsfile=$(echo $escaped_cidr)_hosts.txt
masscanfile=$(echo $escaped_cidr)_masscan.json
nmapoutfile=$(echo $escaped_cidr)_nmap.xml

mkdir $escaped_cidr
cd $escaped_cidr

datestamp=$(date +%Y%m%d)
mkdir $datestamp
cd $datestamp

if [ $# -eq 0 ]; 
then
    echo "USAGE: scan <cidr_or_ip> <additional_ports>"
    exit 1
fi

if [[ $2 ]]
then
	ports=$ports,$2
fi

sudo masscan -v $ports $1 --output-format json --output-file $masscanfile

cat $masscanfile | jq .[].ip | sort | uniq | tr -d '"' > $hostsfile
host_count=$(wc -l $hostsfile | awk '{print $1}')
echo "masscan found $host_count host(s)"

if [[ $host_count > 0 ]]
then
	ports=$(cat $masscanfile | jq .[].ports[].port | sort | uniq | tr '\n' ',')
	ports=${ports::-1}

	sudo nmap -O -sSVC -p $ports -iL $hostsfile -oX $nmapoutfile --webxml
fi

rm $hostsfile