#!/bin/bash

sudo dnsvalidator -tL https://public-dns.info/nameservers.txt -threads 20 -o /opt/dnsvalidator/resolvers.txt

sudo head -25 /opt/dnsvalidator/resolvers.txt > /opt/dnsvalidator/resolvers_top25.txt